### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "3c8b8a1da6ba45c193bd1c7b4175ae28",
  "accountNumber": "1000000000",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/173cffdfa00146bab04f69ac1a1b11c3